package com.atlong.crm.settings.mapper;

import com.atlong.crm.settings.domian.DictionaryType;

import java.util.List;

public interface DictionaryTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Wed Aug 10 16:42:58 CST 2022
     */
    int deleteByPrimaryKey(String code);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Wed Aug 10 16:42:58 CST 2022
     */
    int insertSelective(DictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Wed Aug 10 16:42:58 CST 2022
     */
    DictionaryType selectByPrimaryKey(String code);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Wed Aug 10 16:42:58 CST 2022
     */
    int updateByPrimaryKey(DictionaryType record);
    /**
     * 查询所有的字典类型
    * */
    List<DictionaryType> selectAll();

    /**
     *查询code存在的记录
     * */
    int selectCountByCode(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *新增记录
     * @mbggenerated Wed Aug 10 16:42:58 CST 2022
     */
    int insert(DictionaryType record);

    /**
     *批量删除记录
     * */
    int deleteByCodes(String[] code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *更新记录
     * @mbggenerated Wed Aug 10 16:42:58 CST 2022
     */
    int updateByPrimaryKeySelective(DictionaryType record);

}